function noisy_point = addTwoTypesOfNoise(point, sensor_noise, model_noise)
    if model_noise.type == "additive"
        noisy_point = point + ...
                       [sensor_noise.rand_x + model_noise.x; ...
                        sensor_noise.rand_y + model_noise.y; ...
                        sensor_noise.rand_z + model_noise.z;
                        0; 0];
    elseif model_noise.type == "transformation"
        noisy_point = model_noise.H * point(1:3,:);
        noisy_point = noisy_point  + ...
                       [sensor_noise.rand_x; ...
                        sensor_noise.rand_y; ...
                        sensor_noise.rand_z;
                        0; 0];
    end
end